# Generated by Django 5.1.6 on 2025-02-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playground',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
