# Generated by Django 5.1.6 on 2025-02-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_playground_price_per_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playgroundbooking',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='playgroundbooking',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
