# Generated by Django 5.1.6 on 2025-02-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_playgroundbooking_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playgroundbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
