# Generated by Django 5.1.6 on 2025-02-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_playgroundbooking_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playgroundbooking',
            name='total_price',
        ),
    ]
